/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */


#ifndef __VERSION_H__
#define __VERSION_H__

/*
 *	BuildAll may pass ELASTICDRIVERVERSION, ELASTIC_RESOURCE_VERSION
 *	and OPENSEARCH_DRVFILE_VERSION via winbuild/elasticodbc.vcxproj.
 */
#ifdef OPENSEARCH_ODBC_VERSION

#ifndef OPENSEARCHDRIVERVERSION
#define OPENSEARCHDRIVERVERSION OPENSEARCH_ODBC_VERSION
#endif
#ifndef OPENSEARCH_RESOURCE_VERSION
#define OPENSEARCH_RESOURCE_VERSION OPENSEARCHDRIVERVERSION
#endif
#ifndef OPENSEARCH_DRVFILE_VERSION
#define OPENSEARCH_DRVFILE_VERSION OPENSEARCH_ODBC_DRVFILE_VERSION
#endif

#endif  // OPENSEARCH_ODBC_VERSION

#endif
