FROM opensearchproject/opensearch:2.2.0
RUN rm -rf plugins/opensearch-sql
RUN rm -rf plugins/opensearch-sql-2.2.0.0-SNAPSHOT
COPY opensearch-2.2.0/plugins/opensearch-sql-2.2.0.0-SNAPSHOT plugins/opensearch-sql-2.2.0.0-SNAPSHOT
