---
##
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
##

# Settings file for the .async-query-scheduler index
index:
  number_of_shards: "1"
  auto_expand_replicas: "0-2"
  number_of_replicas: "0"