/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

apply plugin: 'groovy'
apply plugin: 'java'


repositories {
    maven { url "https://ci.opensearch.org/maven2/" }
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
}