version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Los_Angeles"
    labels:
      - "skip-changelog"
    group:
      all-dependencies:
        patterns:
          - "*"
