name: Remove duplicate label on activity

on:
  issue_comment:
    types: [created]

jobs:
  remove-duplicate:
    uses: qianheng-aws/opensearch-build/.github/workflows/issue-dedupe-remove-label.yml@add-issue-dedupe-workflow
    permissions:
      issues: write
