name: SQL Plugin PiTest

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        type: string

run-name:
  ${{ inputs.name == '' && format('{0} @ {1}', github.ref_name, github.sha) || inputs.name }}

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  build-linux:
    needs: Get-CI-Image-Tag
    strategy:
      matrix:
        java:
          - 21
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    runs-on: ubuntu-latest
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: --user root

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: PiTest with Gradle
      run: |
        chown -R 1000:1000 `pwd`
        su `id -un 1000` -c "./gradlew --continue :core:pitest :opensearch:pitest"

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-${{ matrix.entry.java }}
        path: |
          core/build/reports/**
          opensearch/build/reports/**
