name: SQL Plugin PiTest

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        type: string

run-name:
  ${{ inputs.name == '' && format('{0} @ {1}', github.ref_name, github.sha) || inputs.name }}

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: PiTest with Gradle
      run: |
        ./gradlew --continue :core:pitest :opensearch:pitest

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-${{ matrix.entry.java }}
        path: |
          core/build/reports/**
          opensearch/build/reports/**
